apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "100Mi"
      requests:
        memory: "60Mi"
