apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: nginx
    name: test
    resources: {}
  nodeSelector:
    disk: hdd
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
