apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: container
    image: nginx
    env:
      - name: SECRET_USER
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASS
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never
