apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-vol-pod
  name: secret-vol-pod
spec:
  containers:
  - image: nginx
    name: secret-vol-pod
    resources: {}
    volumeMounts:
    - name: foo
      mountPath: /secrets
  volumes:
  - name: foo
    secret:
      secretName: mysecret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
